### ISSUE TITLE
Lua Error when porting to Mount Hyjal

### ISSUE THREAD

**Issue by JacobraPDX** [smaitch/Grail#245]
Every time I port to Mount Hyjal I get the following error:

Message: Interface\AddOns\Grail\Grail.lua:3968: Usage: local powerLevel = C_AzeriteItem.GetPowerLevel(azeriteItemLocation)
Time: Fri Nov 20 22:04:25 2020
Count: 1
Stack: Interface\AddOns\Grail\Grail.lua:3968: Usage: local powerLevel = C_AzeriteItem.GetPowerLevel(azeriteItemLocation)
[string "=[C]"]: in function `GetPowerLevel'
[string "@Interface\AddOns\Grail\Grail.lua"]:3968: in function `AzeriteLevelMeetsOrExceeds'
[string "@Interface\AddOns\Grail\Grail.lua"]:6529: in function `f'
[string "@Interface\AddOns\Grail\Grail.lua"]:3768: in function `_AllEvaluateTrueS'
[string "@Interface\AddOns\Grail\Grail.lua"]:3868: in function <Interface\AddOns\Grail\Grail.lua:3849>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Grail\Grail.lua"]:8178: in function `MeetsPrerequisites'
[string "@Interface\AddOns\Grail\Grail.lua"]:10849: in function `StatusCode'
[string "@Interface\AddOns\Grail\Grail.lua"]:6664: in function `f'
[string "@Interface\AddOns\Grail\Grail.lua"]:3768: in function `_AllEvaluateTrueS'
[string "@Interface\AddOns\Grail\Grail.lua"]:3868: in function <Interface\AddOns\Grail\Grail.lua:3849>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Grail\Grail.lua"]:3785: in function `AncestorStatusCode'
[string "@Interface\AddOns\Grail\Grail.lua"]:10851: in function `StatusCode'
[string "@Interface\AddOns\Grail\Grail.lua"]:4341: in function `ClassificationOfQuestCode'
[string "@Interface\AddOns\Wholly\Wholly.lua"]:1434: in function `_ClassifyQuestsInMap'
[string "@Interface\AddOns\Wholly\Wholly.lua"]:1885: in function `_ForcePanelMapArea'
[string "@Interface\AddOns\Wholly\Wholly.lua"]:4417: in function `UpdateQuestCaches'
[string "@Interface\AddOns\Wholly\Wholly.lua"]:963: in function `?'
[string "@Interface\AddOns\Wholly\Wholly.lua"]:2532: in function `_OnEvent'
[string "@Interface\AddOns\Wholly\Wholly.lua"]:4433: in function <Interface\AddOns\Wholly\Wholly.lua:4433>

Locals:

**Comment by smaitch** [comment]
Portland?  :-)  Are you using Grail 112?  I thought this was fixed in Grail 112.

**Comment by JacobraPDX** [comment]
Yup, I am in the Portland, OR area. :) I am using version 112, and get that error every time.  Let me uninstall, and re-install and see if that fixes it.

**Comment by JacobraPDX** [comment]
Even after re-install, still getting the same error when porting to Mount Hyjal.

**Comment by smaitch** [comment]
The code that Grail 112 is using is:

currentLevel = C_AzeriteItem.GetPowerLevel(C_AzeriteItem.FindActiveAzeriteItem())

I have just tested with a character that does not have an azurite item, and unfortunately C_AzeriteItem.FindActiveAzeriteItem() returns nil, which I imagine it what you are seeing.  Therefore, the next release of Grail will change that line to the following two lines (which you can replace in your Grail.lua file if you want):

local azeriteItemLocation = C_AzeriteItem.FindActiveAzeriteItem()
currentLevel = azeriteItemLocation and C_AzeriteItem.GetPowerLevel(azeriteItemLocation) or 0

**Comment by JacobraPDX** [comment]
Yup, that fixed the problem! TYVM!

**Comment by smaitch** [comment]
Grail 113 is out with the change in place.
